spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order
    username: shilpi
    password: shilpi
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
      show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

rabbitmq:
  host: ${RABBITMQ_HOST:localhost}
  port: 5672
  username: guest
  password: guest
  exchange:
    name: order.exchange
  queue:
    name: order.queue
  routing:
    key: order.tracking

logging:
  level:
    root: INFO
    com.ecommerce.user: TRACE
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
      
#Circuit Brekae
resilience4j:
  circuitbreaker:
    instances:
      productService:
        ignore-exceptions:
          - com.ecommerce.order.exceptionHandling.CartException
          - com.ecommerce.order.exceptionHandling.InsufficientQuantityException
          - com.ecommerce.order.exceptionHandling.ProductNotFoundException
          - com.ecommerce.order.exceptionHandling.ServiceUnavailableException
          - com.ecommerce.order.exceptionHandling.UserNotFoundException


        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based
      
    retry: 
      instances:
        retryBreakar:
            maxAttempts: 5
            waitDuration: 500ms
