spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order
    username: shilpi
    password: shilpi

  rabbitmq:
        host: rabbitmq
        port: 5672
        username: guest
        password: guest  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
